---
title: "TidyTuesday - Spotify Song Analytics"
author: "Riddhi Mehta-Neugebauer"
date: "01/21/2020"
output: html_document
editor_options: 
  chunk_output_type: console
---

```{r}
library(tidyverse);  library(ggthemes); library(lubridate); library(svglite); library(hrbrthemes); library(patchwork) 
```

# Load Data
```{r}
spotify_songs <- readr::read_csv('https://raw.githubusercontent.com/rfordatascience/tidytuesday/master/data/2020/2020-01-21/spotify_songs.csv')

```

# Clean Data
```{r}
# Remove all variables with "_id" 
data <- spotify_songs %>% 
  select(-contains("_id"))

# Make genre and subgenre factors
data$playlist_genre <- as.factor(data$playlist_genre)
data$playlist_subgenre <- as.factor(data$playlist_subgenre)
data$playlist_name <- as.factor(data$playlist_name)
```

# Evolution of Song Descriptors By Decade
## Get data into correct format
```{r}
data_descrip <- data %>% 
  distinct(tolower(track_name), tolower(track_artist), .keep_all = T) %>% 
  mutate(
    track_album_release_date = as.Date(track_album_release_date),
    release_year = as.numeric(str_sub(track_album_release_date, 1, 4)), # start and end position
    decade = (release_year %/% 10) * 10, # get the decade using integer division
    loudness = loudness + 60) # it ranges from -60 to 0 db, so to start it at 0, just add 60.
```

```{r}
data_descrip <- data_descrip %>% 
  pivot_longer(danceability:tempo, names_to = "descriptor") %>% 
  filter(
    descriptor == "danceability" |
    descriptor == "speechiness" |
    descriptor == "valence") %>% 
  mutate(descriptor = toupper(descriptor))
```

## Plot Evolution of Song Descriptors By Decade
Code replicated from: https://github.com/gkaramanis/tidytuesday/blob/master/2020-week04/spotify.R
```{r}
plot_descrip <- ggplot(data_descrip) +
  geom_segment(aes(x = track_album_release_date, xend = track_album_release_date, y = -value/2, yend = value/2), alpha = 0.1, color = "#00A388") +
  scale_x_date(expand = c(0.002, 0.002), breaks = as.Date(c("1960-01-01", "1970-01-01", "1980-01-01", "1990-01-01", "2000-01-01", "2010-01-01", "2020-01-01")), date_labels = "%Y") +
  facet_wrap(vars(descriptor), scales = "free_y", ncol = 1) +
  labs(title = toupper("Evolution of Spotify song descriptors by decade"),
       caption = "Source: Spotify | Replicating Code By: Georgios Karamanis") +
  theme_ipsum(base_family = "IBM Plex Mono",
              caption_size = 12) +
   theme(
     panel.grid.major.x = element_blank(),
     panel.grid.minor.x = element_blank(),
     panel.grid.minor.y = element_blank(),
     panel.grid.major.y = element_blank(),
     axis.text.y = element_blank(),
     axis.title.x = element_blank(),
     axis.title.y = element_blank())

plot_descrip  

ggsave(plot_descrip, file = "./spotify_plot_descrip.svg", width = 14, height = 10)
```


# Speechiness By Genre
## Data
```{r}
data_speechgenre <- data %>% 
  distinct(tolower(track_name), tolower(track_artist), .keep_all = T) %>% 
  mutate(
    track_album_release_date = as.Date(track_album_release_date),
    release_year = as.numeric(str_sub(track_album_release_date, 1, 4)), # start and end position
    decade = (release_year %/% 10) * 10) %>% 
  select(track_name, track_artist, release_year, decade, playlist_genre, speechiness) %>% 
  na.omit(release_year) %>% 
  group_by(decade, playlist_genre) %>% 
  summarize(speech_mean = mean(speechiness))
  
```

## Plot
```{r}
plot_speechgenre <- data_speechgenre %>% 
  ggplot(aes(x = decade, y = speech_mean, group = playlist_genre, color = playlist_genre)) +
  geom_line(size = 2) +
  theme_ipsum(caption_size = 12, 
              axis_text_size = 12,
              axis_title_size = 14,
              axis_title_just = "center",
              plot_title_margin = 10) +
  geom_text(data_speechgenre %>% filter(decade == 2020), mapping = aes(label = playlist_genre,
                                                                     x = decade + 2, 
                                                                     y = speech_mean, 
                                                                     color = playlist_genre),
            size = 5) +
  ylab("Average Speech Rating") +
  xlab("") +
  labs(title = toupper("Average Song Speech Rating By Decade"),
       caption = "Source: Spotify | #TidyTuesday") +
  theme(legend.position = "none") 

ggsave(plot_speechgenre, file = "./spotify_plot_speechgenre.svg", width = 14, height = 10)
  
```

# Patch Grids Together
```{r}
plot_patch <- plot_descrip / plot_speechgenre / plot_annotation(title = toupper("An Exploration of Song Speechiness"), 
                                                                subtitle = "I first followed Georgios Karamanis' lead and assessed how three song descriptors evolved through the decades. \nSpeechiness showed the most noticeable difference over time. Next, I investigated how speechiness has evolved by genre. As expected, rap music \nclearly demonstrates the highest prevalence of the spoken word. But interestingly, the spoken word has decreased in recent years from it's peak in the 1990's. \nNotably, over the same time period, speech has become more prominent in other genres.",
                                                                theme = theme(plot.title = element_text(size = 18, face = "bold")))

ggsave(plot_patch, file="./spotify_plot_patch.svg", width = 28, height = 20)
```

